import type { SeedanceV4Mode } from "../types";

interface ModeCapability {
  inputs: string;
  bestFor: string;
  limits: string;
}

export const MODE_CAPABILITIES: Record<
  SeedanceV4Mode | "text_to_video",
  ModeCapability
> = {
  ugc: {
    inputs: "Avatar image + product image. Optional audio.",
    bestFor:
      "Single-shot creator-style content where the actor holds or shows the product.",
    limits:
      "One actor, one product. No multi-shot sequences — use Multi-Frame.",
  },
  multi_reference: {
    inputs:
      "1–9 reference images, each with a role (appearance / product / background).",
    bestFor:
      "Cinematic shots that need to combine several visual sources (style refs, props, locations).",
    limits:
      "Combined videos ≤ 15s; combined audios ≤ 15s. No structured shot list — use Multi-Frame.",
  },
  multi_frame: {
    inputs: "Script + subject brief (text only).",
    bestFor:
      "2–4 shot sequences (e.g. wide → close-up → reaction) that share a subject.",
    limits:
      "No image input — the API only sees text. Subject continuity comes from textual description. Total duration 4–15s.",
  },
  lipsyncing: {
    inputs: "One avatar image + one audio file.",
    bestFor:
      "Talking-head clips where the audio drives mouth motion.",
    limits:
      "Short lines, mouth visible, minimal competing motion. One avatar, one audio.",
  },
  first_n_last_frames: {
    inputs: "Start image + end image (auto-generated by NanoBanana).",
    bestFor:
      "Smooth A→B transitions where the start and destination scenes are both important.",
    limits:
      "Both frames required. Director writes the bridge prompt.",
  },
  text_to_video: {
    inputs: "Free-text description.",
    bestFor:
      "Concept exploration when you have no reference media yet.",
    limits:
      "No image, video, or audio input. Highest variance — iterate.",
  },
};
