import type { Platform } from "@/lib/types";

export interface HashtagSeedEntry {
  tag: string;
  category: string;
  sub_category: string | null;
  platforms: Platform[];
  popularity_score: number;
  is_branded: boolean;
}

function p(priority: "high" | "medium" | "low"): number {
  return priority === "high" ? 90 : priority === "medium" ? 60 : 30;
}

export const HASHTAG_SEED_DATA: HashtagSeedEntry[] = [
  // ── Brand (19) ──────────────────────────────────────────────
  { tag: "CocoLash", category: "brand", sub_category: null, platforms: ["instagram","tiktok","twitter","facebook","linkedin"], popularity_score: p("high"), is_branded: true },
  { tag: "CocoLashBeauty", category: "brand", sub_category: null, platforms: ["instagram","tiktok","twitter","facebook","linkedin"], popularity_score: p("high"), is_branded: true },
  { tag: "CocoLashLashes", category: "brand", sub_category: null, platforms: ["instagram","tiktok","twitter","facebook","linkedin"], popularity_score: p("high"), is_branded: true },
  { tag: "CocoLashGlow", category: "brand", sub_category: null, platforms: ["instagram","tiktok","twitter","facebook","linkedin"], popularity_score: p("high"), is_branded: true },
  { tag: "CocoLashBabe", category: "brand", sub_category: null, platforms: ["instagram","tiktok","twitter","facebook","linkedin"], popularity_score: p("high"), is_branded: true },
  { tag: "CocoLashApproved", category: "brand", sub_category: null, platforms: ["instagram","tiktok","twitter","facebook","linkedin"], popularity_score: p("high"), is_branded: true },
  { tag: "CocoLashObsessed", category: "brand", sub_category: null, platforms: ["instagram","tiktok","twitter","facebook","linkedin"], popularity_score: p("high"), is_branded: true },
  { tag: "CocoLashQueen", category: "brand", sub_category: null, platforms: ["instagram","tiktok","twitter","facebook","linkedin"], popularity_score: p("high"), is_branded: true },
  { tag: "CocoLashVibes", category: "brand", sub_category: null, platforms: ["instagram","tiktok","twitter","facebook","linkedin"], popularity_score: p("high"), is_branded: true },
  { tag: "TeamCocoLash", category: "brand", sub_category: null, platforms: ["instagram","tiktok","twitter","facebook","linkedin"], popularity_score: p("high"), is_branded: true },
  { tag: "CocoLashFamily", category: "brand", sub_category: null, platforms: ["instagram","tiktok","twitter","facebook","linkedin"], popularity_score: p("high"), is_branded: true },
  { tag: "CocoLashStyle", category: "brand", sub_category: null, platforms: ["instagram","tiktok","twitter","facebook","linkedin"], popularity_score: p("high"), is_branded: true },
  { tag: "MyCocoLash", category: "brand", sub_category: null, platforms: ["instagram","tiktok","twitter","facebook","linkedin"], popularity_score: p("high"), is_branded: true },
  { tag: "CocoLashMoment", category: "brand", sub_category: null, platforms: ["instagram","tiktok","twitter","facebook","linkedin"], popularity_score: p("high"), is_branded: true },
  { tag: "CocoLashReview", category: "brand", sub_category: null, platforms: ["instagram","tiktok","twitter","facebook","linkedin"], popularity_score: p("high"), is_branded: true },
  { tag: "CocoLashResults", category: "brand", sub_category: null, platforms: ["instagram","tiktok","twitter","facebook","linkedin"], popularity_score: p("high"), is_branded: true },
  { tag: "CocoLashTutorial", category: "brand", sub_category: null, platforms: ["instagram","tiktok","twitter","facebook","linkedin"], popularity_score: p("high"), is_branded: true },
  { tag: "CocoLashBeforeAndAfter", category: "brand", sub_category: null, platforms: ["instagram","tiktok","twitter","facebook","linkedin"], popularity_score: p("high"), is_branded: true },
  { tag: "CocoLashLook", category: "brand", sub_category: null, platforms: ["instagram","tiktok","twitter","facebook","linkedin"], popularity_score: p("high"), is_branded: true },

  // ── CocoLash Kit (10) ───────────────────────────────────────
  { tag: "CocoLashKit", category: "cocolash-kit", sub_category: null, platforms: ["instagram","tiktok","twitter","facebook","linkedin"], popularity_score: p("high"), is_branded: true },
  { tag: "LashKitEssentials", category: "cocolash-kit", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "CocoLashStarterKit", category: "cocolash-kit", sub_category: null, platforms: ["instagram","tiktok","twitter","facebook","linkedin"], popularity_score: p("high"), is_branded: true },
  { tag: "LashApplicationKit", category: "cocolash-kit", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "CocoLashKitReview", category: "cocolash-kit", sub_category: null, platforms: ["instagram","tiktok","twitter","facebook","linkedin"], popularity_score: p("high"), is_branded: true },
  { tag: "MyLashKit", category: "cocolash-kit", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "LashKitUnboxing", category: "cocolash-kit", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "CocoLashKitTutorial", category: "cocolash-kit", sub_category: null, platforms: ["instagram","tiktok","twitter","facebook","linkedin"], popularity_score: p("high"), is_branded: true },
  { tag: "LashKitMustHave", category: "cocolash-kit", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "CocoLashKitResults", category: "cocolash-kit", sub_category: null, platforms: ["instagram","tiktok","twitter","facebook","linkedin"], popularity_score: p("high"), is_branded: true },

  // ── Lash Styles (15) ────────────────────────────────────────
  { tag: "NaturalLashes", category: "lash-styles", sub_category: "natural", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "VolumeLashes", category: "lash-styles", sub_category: "volume", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "DramaticLashes", category: "lash-styles", sub_category: "dramatic", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "WispyLashes", category: "lash-styles", sub_category: "wispy", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "FluffyLashes", category: "lash-styles", sub_category: "volume", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "CatEyeLashes", category: "lash-styles", sub_category: "cat-eye", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "SubtleLashes", category: "lash-styles", sub_category: "natural", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BoldLashes", category: "lash-styles", sub_category: "dramatic", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "FullLashes", category: "lash-styles", sub_category: "volume", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "LayeredLashes", category: "lash-styles", sub_category: "hybrid", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "3DLashes", category: "lash-styles", sub_category: "volume", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "MinkStyleLashes", category: "lash-styles", sub_category: "dramatic", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "StripLashes", category: "lash-styles", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "CustomLashes", category: "lash-styles", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "EverydayLashes", category: "lash-styles", sub_category: "natural", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },

  // ── Occasions (15) ──────────────────────────────────────────
  { tag: "WeddingLashes", category: "occasions", sub_category: "wedding", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "DateNightReady", category: "occasions", sub_category: "date-night", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "EverydayGlam", category: "occasions", sub_category: "everyday", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BridalLashes", category: "occasions", sub_category: "wedding", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "PartyLashes", category: "occasions", sub_category: "party", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BirthdayGlam", category: "occasions", sub_category: "party", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "GirlsNightOut", category: "occasions", sub_category: "girls-night", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "PromLashes", category: "occasions", sub_category: "prom", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "GalaReady", category: "occasions", sub_category: "gala", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "FestivalLashes", category: "occasions", sub_category: "festival", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "VacationGlam", category: "occasions", sub_category: "vacation", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BrunchReady", category: "occasions", sub_category: "brunch", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "WorkToNightOut", category: "occasions", sub_category: "everyday", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "SpecialOccasionLashes", category: "occasions", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "RedCarpetLashes", category: "occasions", sub_category: "gala", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },

  // ── Seasonal (12) ───────────────────────────────────────────
  { tag: "SummerGlow", category: "seasonal", sub_category: "summer", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "HolidayGlam", category: "seasonal", sub_category: "holiday", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "FestiveLashes", category: "seasonal", sub_category: "holiday", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "SpringBeauty", category: "seasonal", sub_category: "spring", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "WinterGlam", category: "seasonal", sub_category: "winter", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "FallVibes", category: "seasonal", sub_category: "fall", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "NewYearsGlam", category: "seasonal", sub_category: "new-years", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "ValentinesGlam", category: "seasonal", sub_category: "valentines", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "HalloweenGlam", category: "seasonal", sub_category: "halloween", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "SummerLashes", category: "seasonal", sub_category: "summer", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "HolidayLook", category: "seasonal", sub_category: "holiday", platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "SeasonalBeauty", category: "seasonal", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },

  // ── General Beauty (20) ─────────────────────────────────────
  { tag: "LashGoals", category: "general-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "FalseLashes", category: "general-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "LashLove", category: "general-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "LashAddict", category: "general-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "LashGameStrong", category: "general-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "LashesOnFleek", category: "general-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "LashLife", category: "general-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "LashQueen", category: "general-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "LashBoss", category: "general-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "LashObsessed", category: "general-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "LashesOfTheDay", category: "general-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "LashInspo", category: "general-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BeautyRoutine", category: "general-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "MakeupLover", category: "general-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "GlamSquad", category: "general-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BeautyEssentials", category: "general-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "MakeupMustHave", category: "general-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "GlowUp", category: "general-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "FlawlessMakeup", category: "general-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BeautyTips", category: "general-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },

  // ── Community Engagement (10) ───────────────────────────────
  { tag: "CocoLashCommunity", category: "community-engagement", sub_category: null, platforms: ["instagram","tiktok","twitter","facebook","linkedin"], popularity_score: p("high"), is_branded: true },
  { tag: "LashSisters", category: "community-engagement", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "LashTribe", category: "community-engagement", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "BeautyBabes", category: "community-engagement", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "CocoLashChallenge", category: "community-engagement", sub_category: null, platforms: ["instagram","tiktok","twitter","facebook"], popularity_score: p("high"), is_branded: true },
  { tag: "ShowUsYourLashes", category: "community-engagement", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "LashTransformation", category: "community-engagement", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "BeforeAndAfterLashes", category: "community-engagement", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "LashConfidence", category: "community-engagement", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "CocoLashGlowUp", category: "community-engagement", sub_category: null, platforms: ["instagram","tiktok","twitter","facebook"], popularity_score: p("high"), is_branded: true },

  // ── Application Tips (10) ───────────────────────────────────
  { tag: "LashTutorial", category: "application-tips", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "LashHacks", category: "application-tips", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "LashApplication", category: "application-tips", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "LashTips", category: "application-tips", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "HowToApplyLashes", category: "application-tips", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "LashBeginner", category: "application-tips", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "LashPro", category: "application-tips", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "LashCare", category: "application-tips", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "FirstTimeLashes", category: "application-tips", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "EasyLashApplication", category: "application-tips", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },

  // ── Trending / Viral (30) ───────────────────────────────────
  { tag: "GRWM", category: "trending-viral", sub_category: null, platforms: ["instagram","tiktok"], popularity_score: p("high"), is_branded: false },
  { tag: "GetReadyWithMe", category: "trending-viral", sub_category: null, platforms: ["instagram","tiktok"], popularity_score: p("high"), is_branded: false },
  { tag: "LashCheck", category: "trending-viral", sub_category: null, platforms: ["instagram","tiktok"], popularity_score: p("high"), is_branded: false },
  { tag: "MakeupTransformation", category: "trending-viral", sub_category: null, platforms: ["instagram","tiktok"], popularity_score: p("high"), is_branded: false },
  { tag: "GlowUpChallenge", category: "trending-viral", sub_category: null, platforms: ["instagram","tiktok"], popularity_score: p("medium"), is_branded: false },
  { tag: "MakeupHacks", category: "trending-viral", sub_category: null, platforms: ["instagram","tiktok"], popularity_score: p("medium"), is_branded: false },
  { tag: "BeautyTok", category: "trending-viral", sub_category: null, platforms: ["tiktok"], popularity_score: p("high"), is_branded: false },
  { tag: "MakeupTok", category: "trending-viral", sub_category: null, platforms: ["tiktok"], popularity_score: p("high"), is_branded: false },
  { tag: "LashTok", category: "trending-viral", sub_category: null, platforms: ["tiktok"], popularity_score: p("high"), is_branded: false },
  { tag: "ViralBeauty", category: "trending-viral", sub_category: null, platforms: ["instagram","tiktok"], popularity_score: p("medium"), is_branded: false },
  { tag: "ThatGirl", category: "trending-viral", sub_category: null, platforms: ["instagram","tiktok"], popularity_score: p("high"), is_branded: false },
  { tag: "SoftGlam", category: "trending-viral", sub_category: null, platforms: ["instagram","tiktok"], popularity_score: p("high"), is_branded: false },
  { tag: "CleanGirlAesthetic", category: "trending-viral", sub_category: null, platforms: ["instagram","tiktok"], popularity_score: p("high"), is_branded: false },
  { tag: "ITGirl", category: "trending-viral", sub_category: null, platforms: ["instagram","tiktok"], popularity_score: p("medium"), is_branded: false },
  { tag: "MainCharacterEnergy", category: "trending-viral", sub_category: null, platforms: ["instagram","tiktok"], popularity_score: p("medium"), is_branded: false },
  { tag: "SoftLife", category: "trending-viral", sub_category: null, platforms: ["instagram","tiktok"], popularity_score: p("high"), is_branded: false },
  { tag: "CoquetteAesthetic", category: "trending-viral", sub_category: null, platforms: ["instagram","tiktok"], popularity_score: p("high"), is_branded: false },
  { tag: "GlassySkin", category: "trending-viral", sub_category: null, platforms: ["instagram","tiktok"], popularity_score: p("high"), is_branded: false },
  { tag: "CleanBeauty", category: "trending-viral", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "BeautyHacks", category: "trending-viral", sub_category: null, platforms: ["instagram","tiktok"], popularity_score: p("high"), is_branded: false },
  { tag: "BeautyReels", category: "trending-viral", sub_category: null, platforms: ["instagram"], popularity_score: p("high"), is_branded: false },
  { tag: "DailyGlow", category: "trending-viral", sub_category: null, platforms: ["instagram","tiktok"], popularity_score: p("medium"), is_branded: false },
  { tag: "MakeupReels", category: "trending-viral", sub_category: null, platforms: ["instagram"], popularity_score: p("medium"), is_branded: false },
  { tag: "LuxuryLifestyle", category: "trending-viral", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "GlowSkin", category: "trending-viral", sub_category: null, platforms: ["instagram","tiktok"], popularity_score: p("medium"), is_branded: false },
  { tag: "ViralMakeup", category: "trending-viral", sub_category: null, platforms: ["instagram","tiktok"], popularity_score: p("medium"), is_branded: false },
  { tag: "MakeupTrends", category: "trending-viral", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BeautyFYP", category: "trending-viral", sub_category: null, platforms: ["tiktok"], popularity_score: p("medium"), is_branded: false },
  { tag: "GlowGetter", category: "trending-viral", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "LuxuryBeautyTok", category: "trending-viral", sub_category: null, platforms: ["tiktok"], popularity_score: p("medium"), is_branded: false },

  // ── Melanin Beauty (15) ─────────────────────────────────────
  { tag: "MelaninBeauty", category: "melanin-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "BlackGirlMagic", category: "melanin-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "BrownSkinGirls", category: "melanin-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "MelaninPoppin", category: "melanin-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "BlackGirlGlam", category: "melanin-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "MelaninGlow", category: "melanin-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "BlackBeauty", category: "melanin-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "MelaninQueen", category: "melanin-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BlackGirlMakeup", category: "melanin-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "DarkSkinBeauty", category: "melanin-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "MelaninMakeup", category: "melanin-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "BlackOwnedBeauty", category: "melanin-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "SupportBlackOwned", category: "melanin-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "BlackOwnedBusiness", category: "melanin-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook","linkedin"], popularity_score: p("high"), is_branded: false },
  { tag: "BuyBlack", category: "melanin-beauty", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },

  // ── Eye Makeup (22) ─────────────────────────────────────────
  { tag: "EyeMakeup", category: "eye-makeup", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "EyeShadow", category: "eye-makeup", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "EyeLook", category: "eye-makeup", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "SmokeyEye", category: "eye-makeup", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "CutCrease", category: "eye-makeup", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "WingedEyeliner", category: "eye-makeup", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "CatEye", category: "eye-makeup", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "EyeShadowLook", category: "eye-makeup", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "EyelinerGoals", category: "eye-makeup", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "EyeArtistry", category: "eye-makeup", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "EyeMakeupOfTheDay", category: "eye-makeup", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "EyeMakeupIdeas", category: "eye-makeup", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BoldEyes", category: "eye-makeup", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "LinerLook", category: "eye-makeup", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "EyeMakeupLook", category: "eye-makeup", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "ShadowBlending", category: "eye-makeup", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "EuphoriaMakeup", category: "eye-makeup", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "ColorfulEyes", category: "eye-makeup", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "MetallicEyeshadow", category: "eye-makeup", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "EyeHighlight", category: "eye-makeup", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "EyeFlick", category: "eye-makeup", sub_category: null, platforms: ["instagram","tiktok"], popularity_score: p("low"), is_branded: false },
  { tag: "EyeEditorial", category: "eye-makeup", sub_category: null, platforms: ["instagram","facebook"], popularity_score: p("low"), is_branded: false },

  // ── Self-Care & Wellness (15) ───────────────────────────────
  { tag: "SelfCareSunday", category: "self-care-wellness", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "MeTime", category: "self-care-wellness", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "TreatYourself", category: "self-care-wellness", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "PamperYourself", category: "self-care-wellness", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "LuxuryBeauty", category: "self-care-wellness", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "SelfCareRoutine", category: "self-care-wellness", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "SelfCareMatters", category: "self-care-wellness", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "SelfCareDay", category: "self-care-wellness", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "PamperDay", category: "self-care-wellness", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BeautyRitual", category: "self-care-wellness", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "SelfCareVibes", category: "self-care-wellness", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "TreatYoSelf", category: "self-care-wellness", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "InnerBeauty", category: "self-care-wellness", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "WellnessBeauty", category: "self-care-wellness", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "SelfCareSeason", category: "self-care-wellness", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("low"), is_branded: false },

  // ── Confidence & Empowerment (17) ───────────────────────────
  { tag: "BossLady", category: "confidence-empowerment", sub_category: null, platforms: ["instagram","tiktok","facebook","linkedin"], popularity_score: p("high"), is_branded: false },
  { tag: "GirlPower", category: "confidence-empowerment", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "Empowerment", category: "confidence-empowerment", sub_category: null, platforms: ["instagram","tiktok","facebook","linkedin"], popularity_score: p("high"), is_branded: false },
  { tag: "EmpoweringWomen", category: "confidence-empowerment", sub_category: null, platforms: ["instagram","tiktok","facebook","linkedin"], popularity_score: p("high"), is_branded: false },
  { tag: "FemaleEmpowerment", category: "confidence-empowerment", sub_category: null, platforms: ["instagram","tiktok","facebook","linkedin"], popularity_score: p("high"), is_branded: false },
  { tag: "StrongWomen", category: "confidence-empowerment", sub_category: null, platforms: ["instagram","tiktok","facebook","linkedin"], popularity_score: p("high"), is_branded: false },
  { tag: "WomenSupportingWomen", category: "confidence-empowerment", sub_category: null, platforms: ["instagram","tiktok","facebook","linkedin"], popularity_score: p("high"), is_branded: false },
  { tag: "Unbothered", category: "confidence-empowerment", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "KnowYourWorth", category: "confidence-empowerment", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "ConfidentWomen", category: "confidence-empowerment", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "OwnYourGlow", category: "confidence-empowerment", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "QueenVibes", category: "confidence-empowerment", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "SheSlays", category: "confidence-empowerment", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "WomenWhoInspire", category: "confidence-empowerment", sub_category: null, platforms: ["instagram","tiktok","facebook","linkedin"], popularity_score: p("medium"), is_branded: false },
  { tag: "SheIsBeautiful", category: "confidence-empowerment", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BadAndBooujee", category: "confidence-empowerment", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "SheEmpowers", category: "confidence-empowerment", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("low"), is_branded: false },

  // ── Makeup Looks & Aesthetics (20) ──────────────────────────
  { tag: "BeatFace", category: "makeup-looks-aesthetics", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "FullGlam", category: "makeup-looks-aesthetics", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "MakeupOfTheDay", category: "makeup-looks-aesthetics", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "MakeupLook", category: "makeup-looks-aesthetics", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "MakeupLooks", category: "makeup-looks-aesthetics", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "MakeupInspo", category: "makeup-looks-aesthetics", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "MakeupGoals", category: "makeup-looks-aesthetics", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "MakeupAddict", category: "makeup-looks-aesthetics", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "MakeupJunkie", category: "makeup-looks-aesthetics", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "BaddieAesthetic", category: "makeup-looks-aesthetics", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "GlamLook", category: "makeup-looks-aesthetics", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "NoMakeupMakeup", category: "makeup-looks-aesthetics", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "NaturalBeat", category: "makeup-looks-aesthetics", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "DressYourFace", category: "makeup-looks-aesthetics", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "EditorialMakeup", category: "makeup-looks-aesthetics", sub_category: null, platforms: ["instagram","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BoldMakeup", category: "makeup-looks-aesthetics", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "MakeupLife", category: "makeup-looks-aesthetics", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "EverydayMakeup", category: "makeup-looks-aesthetics", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "GlowMakeup", category: "makeup-looks-aesthetics", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "MakeupByme", category: "makeup-looks-aesthetics", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },

  // ── Beauty Creator & Influencer (16) ────────────────────────
  { tag: "BeautyBlogger", category: "beauty-creator-influencer", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "MUA", category: "beauty-creator-influencer", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "InstaBeauty", category: "beauty-creator-influencer", sub_category: null, platforms: ["instagram"], popularity_score: p("high"), is_branded: false },
  { tag: "BeautyBloggers", category: "beauty-creator-influencer", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "MakeupArtistsworldwide", category: "beauty-creator-influencer", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "ContentCreator", category: "beauty-creator-influencer", sub_category: null, platforms: ["instagram","tiktok","facebook","linkedin"], popularity_score: p("high"), is_branded: false },
  { tag: "BeautyCreator", category: "beauty-creator-influencer", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BeautyInfluencer", category: "beauty-creator-influencer", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "MakeupBlogger", category: "beauty-creator-influencer", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BeautyAddict", category: "beauty-creator-influencer", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BeautyGram", category: "beauty-creator-influencer", sub_category: null, platforms: ["instagram"], popularity_score: p("medium"), is_branded: false },
  { tag: "BeautyCommunity", category: "beauty-creator-influencer", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "MakeupInfluencer", category: "beauty-creator-influencer", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BeautyContent", category: "beauty-creator-influencer", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BeautyLover", category: "beauty-creator-influencer", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "MakeupCommunity", category: "beauty-creator-influencer", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },

  // ── Shopping & Hauls (11) ───────────────────────────────────
  { tag: "MustHave", category: "shopping-hauls", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "HolyGrail", category: "shopping-hauls", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "BeautyHaul", category: "shopping-hauls", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "MakeupHaul", category: "shopping-hauls", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "NewMakeup", category: "shopping-hauls", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BeautyFinds", category: "shopping-hauls", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BeautyProducts", category: "shopping-hauls", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BeautyFavorites", category: "shopping-hauls", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "MakeupFinds", category: "shopping-hauls", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "NewInBeauty", category: "shopping-hauls", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "ShopMyBeauty", category: "shopping-hauls", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("low"), is_branded: false },

  // ── Daily Routines & Lifestyle (14) ─────────────────────────
  { tag: "MorningRoutine", category: "daily-routines-lifestyle", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "NightRoutine", category: "daily-routines-lifestyle", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "DailyRoutine", category: "daily-routines-lifestyle", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "ReadyWithMe", category: "daily-routines-lifestyle", sub_category: null, platforms: ["instagram","tiktok"], popularity_score: p("high"), is_branded: false },
  { tag: "DayInMyLife", category: "daily-routines-lifestyle", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "DailyGlam", category: "daily-routines-lifestyle", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "OfficeGlam", category: "daily-routines-lifestyle", sub_category: null, platforms: ["instagram","tiktok","facebook","linkedin"], popularity_score: p("medium"), is_branded: false },
  { tag: "DateNightGlam", category: "daily-routines-lifestyle", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "NightOutReady", category: "daily-routines-lifestyle", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "FridayGlam", category: "daily-routines-lifestyle", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "DayToNightGlam", category: "daily-routines-lifestyle", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "GlowUpRoutine", category: "daily-routines-lifestyle", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "GymToGlam", category: "daily-routines-lifestyle", sub_category: null, platforms: ["instagram","tiktok"], popularity_score: p("low"), is_branded: false },
  { tag: "WorkdayGlam", category: "daily-routines-lifestyle", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("low"), is_branded: false },

  // ── Beauty Quotes & Inspiration (11) ────────────────────────
  { tag: "GlamLife", category: "beauty-quotes-inspiration", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "LookGoodFeelGood", category: "beauty-quotes-inspiration", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BeautyQuotes", category: "beauty-quotes-inspiration", sub_category: null, platforms: ["instagram","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "GlowFromWithin", category: "beauty-quotes-inspiration", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "QueenEnergy", category: "beauty-quotes-inspiration", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BeautyInspiration", category: "beauty-quotes-inspiration", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "MakeupMood", category: "beauty-quotes-inspiration", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "FeelYourself", category: "beauty-quotes-inspiration", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "FaceArt", category: "beauty-quotes-inspiration", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "DressedToKill", category: "beauty-quotes-inspiration", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BeautyIsYou", category: "beauty-quotes-inspiration", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("low"), is_branded: false },

  // ── Product Review (12) ─────────────────────────────────────
  { tag: "HonestReview", category: "product-review", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "ProductReview", category: "product-review", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "WorthTheHype", category: "product-review", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "FirstImpression", category: "product-review", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("high"), is_branded: false },
  { tag: "BeautyReview", category: "product-review", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "MakeupReview", category: "product-review", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "TriedAndTested", category: "product-review", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BeautyFaves", category: "product-review", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BeautyJunkie", category: "product-review", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "MyHolyGrail", category: "product-review", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BeautyEssential", category: "product-review", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("medium"), is_branded: false },
  { tag: "BeautyTester", category: "product-review", sub_category: null, platforms: ["instagram","tiktok","facebook"], popularity_score: p("low"), is_branded: false },
];

export const HASHTAG_CATEGORIES = [
  "brand",
  "cocolash-kit",
  "lash-styles",
  "occasions",
  "seasonal",
  "general-beauty",
  "community-engagement",
  "application-tips",
  "trending-viral",
  "melanin-beauty",
  "eye-makeup",
  "self-care-wellness",
  "confidence-empowerment",
  "makeup-looks-aesthetics",
  "beauty-creator-influencer",
  "shopping-hauls",
  "daily-routines-lifestyle",
  "beauty-quotes-inspiration",
  "product-review",
] as const;

export type HashtagCategory = (typeof HASHTAG_CATEGORIES)[number];
